const fs = require("fs");
const path = require("path");
const multer = require("multer");
const upload = multer({storage: multer.memoryStorage()});

const {toSafeFilename, resolveTrackPath} = require("../util/util");
const {resolveRedirects} = require("../util/music_util");

function users(app, config, baseDir, musicDir) {
    function userDir(userId) {
        return path.join(baseDir, `accounts/${userId}`);
    }

    function userFile(userId) {
        return path.join(userDir(userId), `userdata.json`);
    }

    function readUsers() {
        if (!fs.existsSync(`${baseDir}/users.json`)) {
            return;
        }
        return JSON.parse(fs.readFileSync(`${baseDir}/users.json`));
    }

    function writeUsers(users) {
        return fs.writeFileSync(`${baseDir}/users.json`, JSON.stringify(users));
    }

    function readUser(userId) {
        const file = userFile(userId);
        if (!fs.existsSync(file)) {
            return {success: false, reason: "Account does not exist"};
        }

        return JSON.parse(fs.readFileSync(file));
    }

    function writeUser(userId, userData) {
        return fs.writeFileSync(userFile(userId), JSON.stringify(userData));
    }

    function readPlays(userId) {
        const file = path.join(userDir(userId), `plays.json`);
        if (!fs.existsSync(file)) {
            const result = {plays: []}
            fs.writeFileSync(file, JSON.stringify(result));
            return result
        }
        return JSON.parse(fs.readFileSync(file));
    }

    function writePlays(userId, data) {
        return fs.writeFileSync(path.join(userDir(userId), `plays.json`), JSON.stringify(data));
    }

    function readList(userId, listId) {
        const file = `${userDir(userId)}/playlists/${listId}/playlist.json`;
        if (!fs.existsSync(file)) {
            return;
        }
        return JSON.parse(fs.readFileSync(file));
    }

    function genPlaylistId() {
        const valid = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        let id = "";
        for (let i = 0; i < 10; i++) {
            id += valid.charAt(Math.round(Math.random() * valid.length));
        }
        return id;
    }

    function setup(baseDir) {
        if (!fs.existsSync(baseDir)) {
            console.log(`User directory ${baseDir} does not exist, creating...`);
            fs.mkdirSync(baseDir, {recursive: true});
        }
        if (!fs.existsSync(`${baseDir}/users.json`)) {
            console.log(`User file ${baseDir} does not exist, creating...`);
            const users = {
                current_user: null,
                users: []
            }
            fs.writeFileSync(`${baseDir}/users.json`, JSON.stringify(users));
        }
        if (!fs.existsSync(`${baseDir}/accounts`)) {
            console.log(`Account directory ${baseDir}/accounts does not exist, creating...`);
            fs.mkdirSync(`${baseDir}/accounts`, {recursive: true});
        }
        const users = readUsers(baseDir);
        users.users.forEach((user) => {
            const userDir = `${baseDir}/accounts/${user.id}`;
            if (!fs.existsSync(userDir)) {
                console.log(`Account directory for ${user.id} does not exist, aborting...`);
                throw new Error(`Account directory for ${user.id} does not exist, even though user is registered`);
            }
            if (!fs.existsSync(`${userDir}/userdata.json`)) {
                throw new Error(`userdata.json for ${user.id} does not exist, even though user is registered`);
            }
        })
    }

    setup(baseDir);


    /**
     * Returns list of basic users aswell as the id of the currently selected user
     **/
    app.get("/api/users", async (req, res) => {
        res.json(readUsers(baseDir));
    });
    /**
     * Creates a new user
     * image -> (optional) Profile Picture
     * name -> Username (id will be generated by using the toSafeFilename method)
     * */
    app.post("/api/users", upload.fields([{name: "image", maxCount: 1}, {name: "name"}]), async (req, res) => {
        const name = req.body.name;
        const id = toSafeFilename(name);
        const path = `/api/users/${id}`;

        const directory = userDir(id);

        if (!fs.existsSync(directory)) {
            fs.mkdirSync(directory, {recursive: true});

            const playlistDir = `${directory}/playlists`;
            if (!fs.existsSync(playlistDir)) {
                fs.mkdirSync(playlistDir, {recursive: true});
            }
            if (!fs.existsSync(`${playlistDir}/liked_songs`)) {
                fs.mkdirSync(`${playlistDir}/liked_songs`, {recursive: true});
            }
            if (fs.existsSync(`${playlistDir}/liked_songs/playlist.json`)) {
                res.json({success: false, reason: "playlist id SOMEHOW already exists"});
                return;
            } else {
                const playlist = {
                    cover: "/api/users/playlists/default_cover",
                    title: "Liked Songs",
                    description: "A collection of songs you like",
                    content: []
                };
                fs.writeFileSync(`${playlistDir}/liked_songs/playlist.json`, JSON.stringify(playlist));
            }


            if (req.files && req.files["image"]) {
                fs.writeFileSync(`${directory}/picture.png`, req.files["image"][0].buffer);
            }

            const pictureExists = fs.existsSync(`${directory}/picture.png`);


            const userdata = {
                name,
                picture: pictureExists ? `/api/users/${id}/picture` : "",
                volume: 1.0,
                radio: [],
                pins: {
                    radios: [],
                    songs: [],
                    playlists: [],
                    artists: [],
                }
            }
            writeUser(id, userdata)


            const users = await readUsers(baseDir);
            users.current_user = id;
            users.users.push({id, path})
            writeUsers(users);

            res.json({success: true, id});
        } else {
            res.json({success: false, reason: "account directory already exists"});
        }

    });
    /**
     * Returns the full userdata of a given userId
     * userId -> safe id string
     **/
    app.get("/api/users/:userId", async (req, res) => {
        const user = req.params.userId;
        const userdata = readUser(user);
        let playlists = [];
        if (fs.existsSync(`${baseDir}/accounts/${user}/playlists`)) {
            const lists = fs.readdirSync(`${baseDir}/accounts/${user}/playlists`);
            for (let list of lists) {
                const listData = {id: list, ...readList(user, list)};
                if (listData) playlists.push(listData);
            }
        }
        if (!("volume" in userdata)) {
            userdata.volume = 1.0;
            writeUser(user, userdata);
        }
        res.json({
            name: userdata.name,
            picture: userdata.picture,
            volume: Math.max(0, Math.min(userdata.volume, 1)),
            playlists,
            radio: userdata.radio,
            pins: userdata.pins
        });
    });
    /**
     * Switches the current_user variable
     * :userId -> the safe id string of the newly selected user
     **/
    app.patch("/api/users/:userId", async (req, res) => {
        const user = req.params.userId;
        if (user === "null") {
            const users = await readUsers(baseDir);
            users.current_user = null;
            writeUsers(users);

            res.json({success: true, user: null});
            return;
        }
        if (!fs.existsSync(`${baseDir}/accounts/${user}`)) {
            res.json({success: false, reason: "account does not exist"});
            return;
        }
        const users = await readUsers(baseDir);
        users.current_user = user;
        writeUsers(users);

        res.json({success: true, user});
    });
    /**
     * Returns the profile picture of a certain user
     * :userId -> the user to which the picture belongs
     **/
    app.get("/api/users/:userId/picture", async (req, res) => {
        const user = req.params.userId;
        const userdata = readUser(user);
        if (userdata.picture && fs.existsSync(path.join(userDir(user), "picture.png"))) {
            res.sendFile(path.resolve(path.join(userDir(user), "picture.png")));
        }
    });
    /**
     * Pins either a
     * - Radio Station
     * - Song
     * - Playlist
     * - Or Artist
     * To the quickplay sidebar of the user
     *
     * :userId -> the safe id string of the user to pin to
     * ?category -> one of the four categories as "radio"|"song"|"playlist"|"artist"
     * ?id -> the id of the item to be pinned (for future use body and complex object to songs work)
     * ?unpin -> unpins the given id rather than pinning it
     **/
    app.get("/api/users/:userId/pin", async (req, res) => {
            const user = req.params.userId;
            const category = req.query.category;
            const id = req.query.id;
            const userData = readUser(user);

            if ("unpin" in req.query) {
                switch (category) {
                    case "radio": {
                        if (userData.pins.radios.some(s => s === id)) userData.pins.radios = userData.pins.radios.filter(s => s !== id);
                        break;
                    }
                    case "song": {
                        if ("artist" in req.query) {
                            if (userData.pins.songs.some(s => s.id === id && s.artist === req.query.artist)) userData.pins.songs = userData.pins.songs.filter(s => (s.id !== id || s.artist !== req.query.artist));
                        } else {
                            res.json({success: false, reason: "artist not provided"});
                        }
                        break;
                    }
                    case "playlist": {
                        if (userData.pins.playlists.some(s => s === id)) userData.pins.playlists = userData.pins.playlists.filter(s => s !== id);
                        break;
                    }
                    case "artist": {
                        if (userData.pins.artists.some(s => s === id)) userData.pins.artists = userData.pins.artists.filter(s => s !== id);
                        break;
                    }
                    default:
                        res.json({success: false, reason: "category does not exist"});
                }
            } else {
                switch (category) {
                    case "radio": {
                        if (!userData.pins.radios.some(s => s === id)) userData.pins.radios.push(id);
                        break;
                    }
                    case "song": {
                        if ("artist" in req.query) {
                            if (!userData.pins.songs.some(s => s.id === id && s.artist === req.query.artist)) userData.pins.songs.push({
                                id,
                                artist: req.query.artist
                            });
                        } else {
                            res.json({success: false, reason: "artist not provided"});
                        }
                        break;
                    }
                    case
                    "playlist"
                    : {
                        if (!userData.pins.playlists.some(s => s === id)) userData.pins.playlists.push(id);
                        break;
                    }
                    case
                    "artist"
                    : {
                        if (!userData.pins.artists.some(s => s === id)) userData.pins.artists.push(id);
                        break;
                    }
                    default:
                        res.json({success: false, reason: "category does not exist"});
                }
            }
            writeUser(user, userData);
            res.json(userData);
        }
    );

    app.get("/api/users/:userId/plays", async (req, res) => {
        res.json(readPlays(req.params.userId));
    })
    app.post("/api/users/:userId/plays", async (req, res) => {
        const userId = req.params.userId;

        const category = req.query.category;
        const id = req.query.id;

        const data = readPlays(userId);

        const timestamp = Date.now();
        const timelimit = (config["recommendations"]["time-limit"] ?? 14) * (24 * 60 * 60 * 1000);
        const minentries = (config["recommendations"]["min-entries"] ?? 50);

        function filterPlays(plays, options = {}) {
            const {
                timeLimit = timelimit,
                minEntries = minentries,
                type = null,
            } = options;

            const cutoff = Date.now() - timeLimit;
            let filtered = plays.filter(p => p.timestamp >= cutoff);

            if (type) filtered = filtered.filter(p => p.type === type);

            if (filtered.length < minEntries) {
                const pool = type ? plays.filter(p => p.type === type) : plays;
                filtered = pool.slice(0, minEntries);
            }

            return filtered;
        }

        switch (category) {
            case "radio": {
                data.plays.unshift({type: "radio", id: id, timestamp});
                break;
            }
            case "song": {
                if ("artist" in req.query) {
                    data.plays.unshift({type: "song", id: id, artist: req.query.artist, timestamp});
                } else {
                    res.json({success: false, reason: "artist not provided"});
                }
                break;
            }
            case
            "playlist"
            : {
                data.plays.unshift({type: "playlist", id: id, timestamp});
                break;
            }
            case
            "artist"
            : {
                data.plays.unshift({type: "artist", id: id, timestamp});
                break;
            }
            default:
                res.json({success: false, reason: "category does not exist"});
        }
        data.plays = filterPlays(data.plays);
        writePlays(userId, data);
        return res.json(data);
    });

    app.patch("/api/users/:userId/volume", async (req, res) => {
        const userdata = readUser(req.params.userId);
        const volume = Math.max(0, Math.min(1, Number(req.query.level)));
        userdata.volume = volume;
        writeUser(req.params.userId, userdata);
        res.json({success: true, volume});
    });
    /**
     * Follows a radio station
     * :userId -> safe id string of the user who should follow the station
     * ?uuid -> the uuid of the radio station as returned by radio-browser (or for this application the route /api/radio?q="..."
     * ?unfollow -> unfollows the given uuid from the users list rather than following it
     **/
    app.get("/api/users/:userId/radio/follow", async (req, res) => {
        const user = req.params.userId;
        const station = req.query.uuid;
        const userdata = readUser(user);
        let radios = userdata.radio;

        if ("unfollow" in req.query && radios.some(r => r.uuid === station)) {
            radios = radios.filter(r => r.uuid !== station);
        } else if (!radios.some(r => r.uuid === station)) {
            const response = await fetch(`https://de1.api.radio-browser.info/json/stations/byuuid/${station}`)
            const result = (await response.json());
            const raw = result[0];
            const resolvedUrl = await resolveRedirects(raw.url_resolved);
            const data = {
                uuid: raw.stationuuid,
                title: raw.name,
                url: {
                    track: resolvedUrl,
                    cover: raw.favicon,
                },
                tags: raw.tags,
            }
            radios.push(data);
        }

        userdata.radio = radios;
        writeUser(user, userdata);
        res.json({success: true, radios: radios});
    });

    /**
     * Creates a new playlist for the user
     * :userId -> safe id string of the user for whom the playlist should be created
     * ?title -> The display title of the playlist
     **/
    app.post("/api/users/:userId/playlists", upload.fields([{
        name: "image",
        maxCount: 1
    }, {name: "description"}, {name: "title"}]), async (req, res) => {
        const user = req.params.userId;
        if (!fs.existsSync(`${userDir(user)}`)) {
            res.json({success: false, reason: "account does not exist"});
            return;
        }
        const id = genPlaylistId();

        const directory = path.join(userDir(user), `playlists/${id}`);
        if (!fs.existsSync(directory)) {
            fs.mkdirSync(directory, {recursive: true});
        }
        if (fs.existsSync(path.join(directory, `playlist.json`))) {
            res.json({success: false, reason: "playlist id SOMEHOW already exists"});
            return;
        }

        const title = req.body.title;
        const description = req.body.description;

        if (req.files && req.files["image"]) {
            fs.writeFileSync(`${directory}/picture.png`, req.files["image"][0].buffer);
        }

        const pictureExists = fs.existsSync(`${directory}/picture.png`);

        const cover = !pictureExists ? "/api/users/playlists/default_cover" : `/api/users/${user}/playlists/${id}/cover`;
        const content = [];

        const playlist = {cover, title, description, content};
        fs.writeFileSync(`${directory}/playlist.json`, JSON.stringify(playlist));

        res.json({success: true, id});
    });

    /**
     * Adds a song to the playlist of the user
     * :userId -> safe id string of the user to whos playlist a song should be added
     * :playlistId -> safe id string of the playlist to which the song should be added
     * ?song -> song id in safe format
     * ?artist -> artist id in safe format
     **/
    app.post("/api/users/:userId/playlists/:playlistId", async (req, res) => {
        const user = req.params.userId;
        if (!fs.existsSync(`${baseDir}/accounts/${user}`)) {
            res.json({success: false, reason: "account does not exist"});
            return;
        }
        const playlist = req.params.playlistId;
        if (!fs.existsSync(`${baseDir}/accounts/${user}/playlists/${playlist}/playlist.json`)) {
            res.json({success: false, reason: "playlist does not exist"});
            return;
        }
        const data = JSON.parse(fs.readFileSync(`${baseDir}/accounts/${user}/playlists/${playlist}/playlist.json`));

        const song = req.query.song;
        const artist = req.query.artist;

        const trackDir = resolveTrackPath(musicDir, artist, song);
        if (trackDir.length > 0) {
            data.content.push(
                trackDir
            )

        }
        fs.writeFileSync(`${baseDir}/accounts/${user}/playlists/${playlist}/playlist.json`, JSON.stringify(data));
        res.json(data);
    });

    /**
     * Returns the default general for all playlists if none was specified
     **/
    app.get("/api/users/playlists/default_cover", (req, res) => {
        res.sendFile(path.resolve(`${baseDir}/cover.png`));
    });

    /**
     * Returns playlist data for a given playlist
     * :userId -> safe id string of the user whos playlist data should be returned
     * :playlistId -> safe playlist id of the list to be returned
     **/
    app.get("/api/users/:userId/playlists/:playlistId", async (req, res) => {
        const user = req.params.userId;
        const playlist = req.params.playlistId;

        if (!fs.existsSync(`${baseDir}/accounts/${user}`)) {
            res.json({success: false, reason: "account does not exist"});
            return;
        }

        const playlistDir = `${baseDir}/accounts/${user}/playlists`;
        const playlistData = JSON.parse(fs.readFileSync(path.join(playlistDir, `${playlist}/playlist.json`)));
        res.json({
            id: playlist,
            title: playlistData.title,
            cover: playlistData.cover,
            description: playlistData.description,
            content: playlistData.content
        });
    });
    /**
     * Returns the playlist cover for a playlist
     **/
    app.get("/api/users/:userId/playlists/:playlistId/cover", async (req, res) => {
        const user = req.params.userId;
        const playlist = req.params.playlistId;

        if (!fs.existsSync(`${baseDir}/accounts/${user}`)) {
            res.json({success: false, reason: "account does not exist"});
            return;
        }
        const playlistDir = `${baseDir}/accounts/${user}/playlists/${playlist}`;
        if (!fs.existsSync(path.join(playlistDir, `picture.png`))) {
            res.json({success: false, reason: "playlist does not exist"});
        } else {
            res.sendFile(path.resolve(path.join(playlistDir, `picture.png`)));
        }
    })
}

module.exports = users;